#!/bin/bash -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$1" ]
then
	ASM="$1"
else
	[ -n "$TMPDIR" ] || TMPDIR=$(mktemp -d)/
	chmod 755 $TMPDIR
	cd $TMPDIR
	cat <<END >shellcode.s
.globl _start
_start:
.intel_syntax noprefix
$1
END
	ASM=shellcode.s
fi

ELF=${ASM%%.s}.elf
RAW=${ASM%%.s}.raw

echo "[+] ASM file: $TMPDIR$ASM"
echo "[+] ELF file: $TMPDIR$ELF"
echo "[+] RAW file: $TMPDIR$RAW"

gcc -static -nostdlib -o $ELF $ASM
objcopy --dump-section .text=$RAW $ELF

$SCRIPT_DIR/analyze ./$ELF $RAW
