#!/bin/bash -e

if [ -f "$1" ]
then
	ASM="$1"
else
	[ -n "$TMPDIR" ] || TMPDIR=$(mktemp -d)/
	chmod 755 $TMPDIR
	cd $TMPDIR
	cat <<END >shellcode.s
.globl _start
_start:
.intel_syntax noprefix
$1
END
	ASM=shellcode.s
fi

ELF=${ASM%%.s}.elf
RAW=${ASM%%.s}.raw

echo "[+] ASM file: $TMPDIR$ASM"
echo "[+] ELF file: $TMPDIR$ELF"
echo "[+] RAW file: $TMPDIR$RAW"

gcc -static -nostdlib -o $ELF $ASM
objcopy --dump-section .text=$RAW $ELF

echo
objdump -M intel -d $ELF | tail -n+8 | sed -e "s/^ */[-] /"

echo
hd $RAW | head -n-1 | sed -e "s/^ */[-] /"

echo
echo "[+] C"
xxd -i -a $RAW

echo
echo "[+] python2"
echo "shellcode = \"$(xxd -p -a -c 256 $RAW)\".decode(\"hex\")"

echo
echo "[+] python3"
echo "shellcode = \"$(xxd -p -a -c 256 $RAW)\".unhex()"

echo
echo "[-] SIZE: $(du -sb $RAW)"

grep -lPaq '\x00' shellcode.raw && echo "[!] CHECK: \0 found."
grep -lPaq '\x0a' shellcode.raw && echo "[!] CHECK: \n found."
grep -lPaq '\x0d' shellcode.raw && echo "[!] CHECK: \r found."
grep -lPaq '\x20' shellcode.raw && echo "[!] CHECK: Spaces found."

echo
echo "[-] strace"
sudo -u nobody strace -b execve ./$ELF 2>&1 | sed -u -e "s/^/[-] /" | head -n-1

