#!/bin/bash -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONSOLE=0
while getopts "c" OPT
do
        case $OPT in
                c)
                        CONSOLE=1
                        ;;
                ?)
                        OPTIND=$(($OPTIND-1))
                        break
                        ;;
        esac
done
shift $((OPTIND-1))


if [ -f "$1" ]
then
	ASM="$1"
else
	[ -n "$TMPDIR" ] || TMPDIR=$(mktemp -d)/
	chmod 755 $TMPDIR
	cd $TMPDIR
	cat <<END >shellcode.s
.globl _start
_start:
.intel_syntax noprefix
$1
END
	ASM=shellcode.s
fi

ELF=${ASM%%.s}.elf
RAW=${ASM%%.s}.raw

gcc -static -nostdlib -o $ELF $ASM
objcopy --dump-section .text=$RAW $ELF

if [ "$CONSOLE" -eq 0 ]
then
	echo "[+] ASM file: $TMPDIR$ASM"
	echo "[+] ELF file: $TMPDIR$ELF"
	echo "[+] RAW file: $TMPDIR$RAW"

	$SCRIPT_DIR/analyze ./$ELF $RAW
else
	cat $RAW
fi
