#!/bin/bash

if [ $# -eq 2 ]
then
	ARCH=$1
	SYSCALL=$2
elif [ $# -eq 1 ]
then
	ARCH=$(uname -m)
	SYSCALL=$1
fi

SYSCALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/syscalls

if [ ! -f $SYSCALL_DIR/$ARCH.tbl ]
then
	echo "Don't know about architecture $ARCH. Architecture list:"
	echo 
	ls $SYSCALL_DIR | sed -e "s/^/\t/" -e "s/.tbl$//"
	exit 1
fi

if [[ $SYSCALL =~ ^-?[0-9]+$ ]]
then
	grep -P "^$SYSCALL\t" $SYSCALL_DIR/$ARCH.tbl | cut -f3
else
	grep -P "\t$SYSCALL\t" $SYSCALL_DIR/$ARCH.tbl | cut -f1
fi | head -n1

