#!/bin/bash -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TMPDIR=$(mktemp -d)/
cp $1 $TMPDIR/shellcode.raw
chmod 755 $TMPDIR
cd $TMPDIR
cat <<END >shellcode.s
.globl _start
_start:
.intel_syntax noprefix
pop rax
END
ASM=shellcode.s
ELF=${ASM%%.s}.elf
RAW=${ASM%%.s}.raw

gcc -static -nostdlib -o $ELF $ASM
objcopy --update-section .text=$RAW $ELF

$SCRIPT_DIR/analyze ./$ELF
