#!/bin/bash

ARCH=x86_64
while getopts "ha:" OPT
do
        case $OPT in
                a) ARCH=$OPTARG ;;
                h)
                        echo "$0 [OPTIONS] SYSCALL"
                        echo ""
                        echo "Lookup syscall given number or number given syscall."
                        echo ""
                        echo "Options:"
                        echo "	-a ARCH		architecture (default: x86_64)"
                        echo "	-h		this help"
                        exit
                        ;;
                ?)
                        OPTIND=$(($OPTIND-1))
                        break
                        ;;
        esac
done
shift $((OPTIND-1))

SYSCALL=$1
SYSCALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/../syscalls

if [ ! -f $SYSCALL_DIR/$ARCH.tbl ]
then
	echo "Don't know about architecture $ARCH. Architecture list:"
	echo 
	ls $SYSCALL_DIR | sed -e "s/^/\t/" -e "s/.tbl$//"
	exit 1
fi

if [[ $SYSCALL =~ ^-?[0-9]+$ ]]
then
	grep -P "^$SYSCALL\t" $SYSCALL_DIR/$ARCH.tbl | cut -f3
else
	grep -P "\t$SYSCALL\t" $SYSCALL_DIR/$ARCH.tbl | cut -f1
fi | head -n1

