name: Run Tests
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        apt-cache search "gcc-[a-z0-9A-Z]*-linux-gnu" | grep ^g | sed -e "s|/.*||" | xargs sudo apt-get install -y
        sudo apt-get install -y strace xxd bsdmainutils
    - name: Test
      run: ./test.sh
